### ISSUE TITLE
[feature request] add options to disable any feature that this plugin applies

### ISSUE THREAD

**Issue by otanim** [shufo/prettier-plugin-blade#113]
i.e. I only want to apply tailwind class sortation logic, while I don't want to change the indents.

basically - having the "blade" parser as is without external prettifying modifications.

**Comment by shufo** [comment]
If you only want to sort tailwind classes, https://github.com/tailwindlabs/prettier-plugin-tailwindcss might be the right solution.

Or you can use https://github.com/shufo/tailwindcss-class-sorter which is used in this plugin.

Currently there doesn't seem to be a parser-only solution for blade that I'm aware of. This is because blade is basically implemented by regular expression string replacement rather than a formal grammar, which makes it difficult to implement a parser...

**Comment by otanim** [comment]
Hey @shufo, thanks for the quick reply, I appreciate it.

> If you only want to sort tailwind classes, https://github.com/tailwindlabs/prettier-plugin-tailwindcss might be the right solution.

Unfortunately, it doesn't work with `.blade.php` files, and if I override the parser using `html` parser, it will mess up with blade directives, even though it will do it's job of "sorting tailwind classes".

> Or you can use https://github.com/shufo/tailwindcss-class-sorter which is used in this plugin.

the whole idea in my case is to override current working files during the development once `prettifier` got executed. That being said `tailwindcss-class-sorter` is only the core feature of sorting tailwindcss classes, which isn't something that directly solves the issue.

I'm more curious if it's possible to set ["Disabling format in file"](https://github.com/shufo/prettier-plugin-blade#disabling-format-in-file) not just for **a line** or **a code block** but **completely disable it**.
![image](https://user-images.githubusercontent.com/7108843/178143681-a96bc2c9-400a-4be8-8c73-ffdd228760de.png)

**Comment by shufo** [comment]
Thanks for description. I might understood what your use case. 

How about [rustywind](https://github.com/avencera/rustywind)? It's not prettier plugin but works fine with blade files.
If you want disabling format per file, `.prettierignore` might be the right solution.
