### ISSUE TITLE
Gigantic css line after reformatting (PHPstorm)

### ISSUE THREAD

**Issue by Blinks44** [shufo/prettier-plugin-blade#146]
Hello! Thank you for an awesome plugin. Can you help me to understand maybe i'm doing something wrong? When i typing tailwind classes, phpstorm automatically transfer classes to a new line after i reach 120 symbols, but then prettier blade plugin starts to sorting tailwind classes and moves all classes from several lines to a gigantic one. If i disable sortTailwindcssClasses in .prettierrc, then everything works as expected, of course without tailwind sorting :(

Maybe i am doing something wrong?

Before prettier
![2022-09-13_22-45-19](https://user-images.githubusercontent.com/8570193/189997135-2eda6350-7f82-4268-ad1c-dc5ff8f8d94a.png)

After prettier
![2022-09-13_22-45-30](https://user-images.githubusercontent.com/8570193/189997143-40ce0ef6-30d5-4b0d-a018-ee853ace05b7.png)

**Comment by shufo** [comment]
Hi @Blinks44. Thanks for trying out.
The reason for this behaviour is that since [Prettier 2.5](https://stackoverflow.com/a/73508953), the classes are now combined into a single line, so this plugin follows that behaviour too.

**Comment by Blinks44** [comment]
> Hi @Blinks44. Thanks for trying out. The reason for this behaviour is that since [Prettier 2.5](https://stackoverflow.com/a/73508953), the classes are now combined into a single line, so this plugin follows that behaviour too.

For what reason they did it, absolutely unreadable...?) Don't you know is it possible to disable this behaviour?

**Comment by shufo** [comment]
@Blinks44 
Perhaps this issue helps you understand why they changed the behaviour. 
https://github.com/prettier/prettier/issues/10918

I think single-line approach is not bad because other html attribute will be more recognizable and increase consistency for team development.
Also if we use ruler-based line breaking, a small change could cause a large line changes.

Disabling this behavior does not seem to be currently supported by Prettier either.
